tags:
    - name: Session
    - name: Search

paths:
    /session/upsert:
        post:
            tags:
                - Session
            summary: Upsert session data
            description: Create or update session data for a specific session ID
            operationId: upsertSession
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                session_id:
                                    type: string
                                    description: Unique session identifier
                                    example: "session_123"
                                data:
                                    type: object
                                    properties:
                                        user_name:
                                            type: string
                                            description: User's name
                                            example: "John Doe"
                                        user_email:
                                            type: string
                                            description: User's email address
                                            example: "john@example.com"
                                        current_time:
                                            type: string
                                            description: Current timestamp
                                            example: "2024-01-15T10:30:00Z"
                                        time_query:
                                            type: array
                                            items:
                                                type: object
                                                properties:
                                                    start_time:
                                                        type: string
                                                        example: "09:00"
                                                    end_time:
                                                        type: string
                                                        example: "17:00"
                                        topic:
                                            type: string
                                            description: Session topic
                                            example: "attendance tracking"
                                        prev_question:
                                            type: string
                                            description: Previous question asked
                                            example: "What is my attendance rate?"
                            required:
                                - session_id
                                - data
            responses:
                '200':
                    description: Session upserted successfully
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    success:
                                        type: boolean
                                        example: true
                                    message:
                                        type: string
                                        example: "Session upserted successfully"
                '400':
                    description: Bad Request - Session ID or data is required
                '412':
                    description: Precondition Failed - Body not provided
                '500':
                    description: Internal server error

    /session/{session_id}:
        get:
            tags:
                - Session
            summary: Get session data
            description: Retrieve session data by session ID
            operationId: getSession
            parameters:
                - in: path
                  name: session_id
                  required: true
                  schema:
                      type: string
                  description: Session ID to retrieve
                  example: "session_123"
            responses:
                '200':
                    description: Session data retrieved successfully
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    user_name:
                                        type: string
                                        example: "John Doe"
                                    user_email:
                                        type: string
                                        example: "john@example.com"
                                    current_time:
                                        type: string
                                        example: "2024-01-15T10:30:00Z"
                                    time_query:
                                        type: array
                                        items:
                                            type: object
                                            properties:
                                                start_time:
                                                    type: string
                                                    example: "09:00"
                                                end_time:
                                                    type: string
                                                    example: "17:00"
                                    topic:
                                        type: string
                                        example: "attendance tracking"
                                    prev_question:
                                        type: string
                                        example: "What is my attendance rate?"
                '400':
                    description: Bad Request - Session ID is required
                '404':
                    description: Session not found
                '500':
                    description: Internal server error

    /search/time:
        post:
            tags:
                - Search
            summary: Search attendance records by time range
            description: Search employee attendance records within specified time periods
            operationId: searchTime
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                user_email:
                                    type: string
                                    description: Employee email address
                                    example: "john.doe@example.com"
                                time_query:
                                    type: array
                                    description: Array of time periods to search within
                                    items:
                                        type: object
                                        properties:
                                            start_time:
                                                type: string
                                                description: Start date in YYYY-MM-DD format
                                                example: "2024-01-01"
                                            end_time:
                                                type: string
                                                description: End date in YYYY-MM-DD format
                                                example: "2024-01-31"
                                        required:
                                            - start_time
                                            - end_time
                                    minItems: 1
                            required:
                                - user_email
                                - time_query
            responses:
                '200':
                    description: Attendance records retrieved successfully
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    data:
                                        type: array
                                        items:
                                            type: object
                                            properties:
                                                date:
                                                    type: string
                                                    description: Date in YYYY-MM-DD format
                                                    example: "2024-01-15"
                                                checkin_time:
                                                    type: string
                                                    description: Check-in time in ISO 8601 UTC format
                                                    example: "2024-01-15T08:30:00.000Z"
                                                checkout_time:
                                                    type: string
                                                    description: Check-out time in ISO 8601 UTC format
                                                    example: "2024-01-15T17:30:00.000Z"
                '400':
                    description: Bad Request - Invalid input parameters
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    error:
                                        type: string
                                        example: "user_email is required and cannot be empty"
                '412':
                    description: Precondition Failed - Request body not provided
                '500':
                    description: Internal server error

    /search/late:
        post:
            tags:
                - Search
            summary: Search late attendance records by time range
            description: Search employee late attendance records within specified time periods
            operationId: searchLate
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                user_email:
                                    type: string
                                    description: Employee email address
                                    example: "john.doe@example.com"
                                time_query:
                                    type: array
                                    description: Array of time periods to search within
                                    items:
                                        type: object
                                        properties:
                                            start_time:
                                                type: string
                                                description: Start date in YYYY-MM-DD format
                                                example: "2024-01-01"
                                            end_time:
                                                type: string
                                                description: End date in YYYY-MM-DD format
                                                example: "2024-01-31"
                                        required:
                                            - start_time
                                            - end_time
                                    minItems: 1
                            required:
                                - user_email
                                - time_query
            responses:
                '200':
                    description: Late attendance records retrieved successfully
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    data:
                                        type: array
                                        items:
                                            type: object
                                            properties:
                                                date:
                                                    type: string
                                                    description: Date in YYYY-MM-DD format
                                                    example: "2024-01-15"
                                                is_late:
                                                    type: boolean
                                                    description: Whether the employee was late on this date
                                                    example: true
                '400':
                    description: Bad Request - Invalid input parameters
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    error:
                                        type: string
                                        example: "user_email is required and cannot be empty"
                '412':
                    description: Precondition Failed - Request body not provided
                '500':
                    description: Internal server error

    /search/attendance:
        post:
            tags:
                - Search
            summary: Search attendance counts by time range
            description: Search employee attendance count records within specified time periods
            operationId: searchAttendance
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                user_email:
                                    type: string
                                    description: Employee email address
                                    example: "john.doe@example.com"
                                time_query:
                                    type: array
                                    description: Array of time periods to search within
                                    items:
                                        type: object
                                        properties:
                                            start_time:
                                                type: string
                                                description: Start date in YYYY-MM-DD format
                                                example: "2024-01-01"
                                            end_time:
                                                type: string
                                                description: End date in YYYY-MM-DD format
                                                example: "2024-01-31"
                                        required:
                                            - start_time
                                            - end_time
                                    minItems: 1
                            required:
                                - user_email
                                - time_query
            responses:
                '200':
                    description: Attendance count records retrieved successfully
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    data:
                                        type: array
                                        items:
                                            type: object
                                            properties:
                                                date:
                                                    type: string
                                                    description: Date in YYYY-MM-DD format
                                                    example: "2024-01-15"
                                                attendance:
                                                    type: number
                                                    description: Attendance count for this date (as float)
                                                    example: 1.0
                '400':
                    description: Bad Request - Invalid input parameters
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    error:
                                        type: string
                                        example: "user_email is required and cannot be empty"
                '412':
                    description: Precondition Failed - Request body not provided
                '500':
                    description: Internal server error

components:
    responses:

    schemas:

    securitySchemes:
