"""init db

Revision ID: f61b830206e2
Revises: 
Create Date: 2025-08-05 11:19:41.015270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f61b830206e2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_attendance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=False),
    sa.Column('checkin_time', sa.DateTime(), nullable=False),
    sa.Column('checkout_time', sa.DateTime(), nullable=True),
    sa.Column('is_late', sa.Boolean(), nullable=True),
    sa.Column('attendance_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('employee_attendance_pkey'))
    )
    op.create_index(op.f('employee_attendance_id_idx'), 'employee_attendance', ['id'], unique=False)
    op.create_index(op.f('employee_attendance_user_email_idx'), 'employee_attendance', ['user_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('employee_attendance_user_email_idx'), table_name='employee_attendance')
    op.drop_index(op.f('employee_attendance_id_idx'), table_name='employee_attendance')
    op.drop_table('employee_attendance')
    # ### end Alembic commands ###
