[project]
name = "src"
version = "0.1.0"
description = ""
requires-python = ">=3.10,<4.0"
dependencies = [
    "python-dotenv==1.1.0",
    "mcp",
]

[tool.uv]
dev-dependencies = [
    "pipdeptree==2.26.1",
]
